name: Package Nodejs Plugin
on: [push]
jobs:
  build:
    name: Build
    # 运行平台， windows-latest目前是windows server 2019 
    # 参考文档 https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
    runs-on: windows-latest

    env:
      targetName: CSPGuildBot
    # 步骤
    steps:
      # 拉取代码
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      #打包js文件
      - name: Package JavaScript File
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir D:/out/JsMain
          mkdir D:/out/JsMain/libs
          cp index.js D:/out/JsMain
          cp package.json D:/out/JsMain
          cp libs/* D:/out/JsMain/libs

      #打包Config文件
      - name: Package Config File
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir D:/out/package/guildBot
          cp guildBot/* D:/out/package/guildBot

      #打包成zip文件
      - name: Compress to zip
        run: |
          7z a D:/out/zip/guildbot.llplugin D:/out/JsMain/*
          cp D:/out/zip/guildbot.llplugin D:/out/package/
          7z a D:/out/zip/CSPGuildBot_${{ github.ref }}.zip D:/out/package/*
        shell: bash

      #上传Action文件
      - name: Upload Action File
        uses: actions/upload-artifact@v1.0.0
        with:
          name: CSPGuildBot
          path: D:/out/package

      #发布Github Release
      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          name: v${{ github.ref }}
          body_path: ./CHANGELOG.md
          files: |
            D:/out/zip/CSPGuildBot_${{ github.ref }}.zip
        env:
            GITHUB_REPOSITORY: CSPDevTeam/CSPGuildBot

  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      #读取更新消息
      - name: Format ChangeLog
        uses: mkungla/actions-set-text-output@v1
        id: get-changelog
        if: startsWith(github.ref, 'refs/tags/')
        with:
          text: ${{ github.event.commits[0].message }}

      #发布Minebbs Release
      - name: Update MineBBS infomation
        uses: fjogeleit/http-request-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          url: 'https://api.minebbs.com/api/openapi/v1/resources/4537/update'
          method: 'POST'
          customHeaders: '{"Authorization": "Bearer ${{ secrets.MINEBBSKEY }}"}'
          contentType: 'application/json'
          data: '{"title": "${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }}", "description": "${{ steps.get-changelog.outputs.value }}", "new_version": "${{ github.ref }}", "file_url": "https://github.com/CSPDevTeam/CSPGuildBot/releases/latest"}'
          escapeData: 'true'
          preventFailureOnNoResponse: 'true'
          ignoreStatusCodes: '400,404,401,500'
      
