name: Package Nodejs Plugin
on: 
  push:
    path:
      - package.json
      - package-lock.json
      - index.js
      - .github/workflows/windows.yml
      - libs/*.*
  pull_request:
    path:
      - package.json
      - package-lock.json
      - index.js
      - .github/workflows/windows.yml
      - libs/*.*
jobs:
  build:
    name: Build
    # 运行平台， windows-latest目前是windows server 2019 
    # 参考文档 https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
    runs-on: windows-latest

    env:
      targetName: CSPGuildBot
    # 步骤
    steps:
      # 拉取代码
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      #打包js文件
      - name: Package JavaScript File
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir D:/out/JsMain
          mkdir D:/out/JsMain/libs
          cp index.js D:/out/JsMain
          cp package.json D:/out/JsMain
          cp libs/* D:/out/JsMain/libs

      #打包Config文件
      - name: Package Config File
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir D:/out/package/guildBot
          cp guildBot/* D:/out/package/guildBot

      #打包成zip文件
      - name: Compress to zip
        run: |
          7z a D:/out/zip/guildbot.llplugin D:/out/JsMain/*
          cp D:/out/zip/guildbot.llplugin D:/out/package/
          7z a D:/out/zip/CSPGuildBot_${{ github.ref }}.zip D:/out/package/*
        shell: bash

      #上传Action文件
      - name: Upload Action File
        uses: actions/upload-artifact@v1.0.0
        with:
          name: CSPGuildBot
          path: D:/out/package

      #发布Github Release
      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          name: v${{ github.ref_name }}
          body_path: ./CHANGELOG.md
          files: |
            D:/out/zip/CSPGuildBot_${{ github.ref_name }}.zip
        env:
            GITHUB_REPOSITORY: CSPDevTeam/CSPGuildBot

      #发布Minebbs Release
      - name: Update MineBBS infomation
        uses: HuoHuas001/Minebbs-Auto-Release@v1.0.4
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          resources: '4537'
          token: ${{ secrets.MINEBBSKEY }}
          title: ${{ github.ref_name }}
          new_version: ${{ github.ref_name }}
          description_file: './CHANGELOG.md'
          file_url: 'https://github.com/CSPDevTeam/CSPGuildBot/releases/latest'

      
      
